### ISSUE TITLE
Documentación del Proyecto Final

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/proyecto-final-equipo-ybjs-jun#2]
Tome en cuenta la siguiente rúbrica para su evaluación.

[Rúbrica de Proyecto Final.docx](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipo-ybjs-jun/files/6781807/Rubrica.de.Proyecto.Final.docx)

También, tratamos de hacer un informe de todo lo que conlleva el proyecto de la empresa Huerto el Mamey... Desde la producción, hasta la manufactura y consumo.

**Comment by Brisa-4** [comment]
Documentación Proyecto Final.

[Sistema Contable con BD y Formularios de la Empresa Huerto el Mamey.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipo-ybjs-jun/files/6785807/Sistema.Contable.con.BD.y.Formularios.de.la.Empresa.Huerto.el.Mamey.pdf)

**Comment by Lissete7** [comment]
[Rubrica.de.Proyecto.Finaley.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipo-ybjs-jun/files/6786148/Rubrica.de.Proyecto.Finaley.pdf)


Calificación = 80

**Comment by Yabin-2021** [comment]
Las lista de figuras está implícita en el Documento, favor de verificar

**Comment by josealfredo79** [comment]
Bien hecho y realizado
